config/routes.rb
Rails.application.routes.draw do
  resources :details
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/detail.rb
class Detail < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: %i[ show edit update destroy ]

  # GET /details or /details.json
  def index
    @details = Detail.all
  end

  # GET /details/1 or /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details or /details.json
  def create
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to detail_url(@detail), notice: "Detail was successfully created." }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1 or /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to detail_url(@detail), notice: "Detail was successfully updated." }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1 or /details/1.json
  def destroy
    @detail.destroy

    respond_to do |format|
      format.html { redirect_to details_url, notice: "Detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def detail_params
      params.require(:detail).permit(:Name, :age, :gender, :Designation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_detail.html.erb
<div id="<%= dom_id detail %>">
  <p>
    <strong>Name:</strong>
    <%= detail.Name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= detail.age %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= detail.gender %>
  </p>

  <p>
    <strong>Designation:</strong>
    <%= detail.Designation %>
  </p>

</div>

app/views/details/_form.html.erb
<%= form_with(model: detail) do |form| %>
  <% if detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
        <% detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Name, style: "display: block" %>
    <%= form.text_field :Name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :Designation, style: "display: block" %>
    <%= form.text_field :Designation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing detail</h1>

<%= render "form", detail: @detail %>

<br>

<div>
  <%= link_to "Show this detail", @detail %> |
  <%= link_to "Back to details", details_path %>
</div>

app/views/details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Details</h1>

<div id="details">
  <% @details.each do |detail| %>
    <%= render detail %>
    <p>
      <%= link_to "Show this detail", detail %>
    </p>
  <% end %>
</div>

<%= link_to "New detail", new_detail_path %>

app/views/details/new.html.erb
<h1>New detail</h1>

<%= render "form", detail: @detail %>

<br>

<div>
  <%= link_to "Back to details", details_path %>
</div>

app/views/details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @detail %>

<div>
  <%= link_to "Edit this detail", edit_detail_path(@detail) %> |
  <%= link_to "Back to details", details_path %>

  <%= button_to "Destroy this detail", @detail, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>